Description: >
    This template deploys an CloudFront distribution

Parameters:

    S3BucketDNSName:
        Description: Name of a S3 Bucket to point to
        Type: String

    CloudFrontOAI:
        Description: Origin Access Identity to create via the CLI
        Type: String

    CertificateArn:
        Description: CertificateArn to create via the CLI. Must be in region us-east-1 to work with CloudFront
        Type: String

    CDNAlias:
        Description: DNS Alias for your CloudFront distribution (for example files.laravelaws.com)
        Type: String

Resources:

    CloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName: !Ref S3BucketDNSName
                      Id: myS3Origin
                      S3OriginConfig:
                          OriginAccessIdentity: !Ref CloudFrontOAI
                Enabled: 'true'
                Aliases:
                    - !Ref CDNAlias
                DefaultCacheBehavior:
                    Compress: 'true'
                    AllowedMethods:
                        - GET
                        - HEAD
                        - OPTIONS
                    TargetOriginId: myS3Origin
                    ForwardedValues:
                        QueryString: 'false'
                        Cookies:
                           Forward: none
                    ViewerProtocolPolicy: redirect-to-https
                ViewerCertificate:
                    AcmCertificateArn: !Ref CertificateArn
                    SslSupportMethod: 'sni-only'

Outputs:

    CFDistributionDomainName:
        Description: Domain name for the CloudFront distribution
        Value: !GetAtt CloudFrontDistribution.DomainName
